blank_issues_enabled: false
contact_links:
  - name: 💬 Discord server
    url: https://discord.gg/2SUWKFnHSm
    about: Chat with the project community.
  - name: 📖 Wiki
    url: https://github.com/Tyrrrz/YoutubeDownloader/wiki
    about: Find usage guides and frequently asked questions.
  - name: 🗨 Discussions
    url: https://github.com/Tyrrrz/YoutubeDownloader/discussions/new
    about: Ask and answer questions.